repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        files: (?i)\.(json|js|jsx|ts|tsx)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.21.0
    hooks:
      - id: eslint
        files: (?i)\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - 'eslint@^7.21.0'
          - 'eslint-plugin-react@^7.22.0'
          - 'eslint-plugin-react-hooks@^4.2.0'
          - 'eslint-plugin-import@^2.22.1'
          - 'eslint-plugin-jsx-a11y@^6.4.1'
          - 'eslint-config-prettier@^8.1.0'